package com.salonig.studentdemo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {

    @Id(autoincrement = true)
    private Long id;
    private Integer address_position;
    private String roll_no;
    private String full_name;
    private java.util.Date date;
    private Boolean gender;
    private Integer course_position;
    private String course_name;
    private String image_path;
    private String address_name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    @Generated
    public Student(Long id, Integer address_position, String roll_no, String full_name, java.util.Date date, Boolean gender, Integer course_position, String course_name, String image_path, String address_name) {
        this.id = id;
        this.address_position = address_position;
        this.roll_no = roll_no;
        this.full_name = full_name;
        this.date = date;
        this.gender = gender;
        this.course_position = course_position;
        this.course_name = course_name;
        this.image_path = image_path;
        this.address_name = address_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAddress_position() {
        return address_position;
    }

    public void setAddress_position(Integer address_position) {
        this.address_position = address_position;
    }

    public String getRoll_no() {
        return roll_no;
    }

    public void setRoll_no(String roll_no) {
        this.roll_no = roll_no;
    }

    public String getFull_name() {
        return full_name;
    }

    public void setFull_name(String full_name) {
        this.full_name = full_name;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getGender() {
        return gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public Integer getCourse_position() {
        return course_position;
    }

    public void setCourse_position(Integer course_position) {
        this.course_position = course_position;
    }

    public String getCourse_name() {
        return course_name;
    }

    public void setCourse_name(String course_name) {
        this.course_name = course_name;
    }

    public String getImage_path() {
        return image_path;
    }

    public void setImage_path(String image_path) {
        this.image_path = image_path;
    }

    public String getAddress_name() {
        return address_name;
    }

    public void setAddress_name(String address_name) {
        this.address_name = address_name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
